[build]
  command = "npm run build"
  publish = ".next"
  # Only build on releases - ignore all other builds
  ignore = "git describe --exact-match HEAD || exit 1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Context-specific build settings
[context.production]
  command = "npm run build"
  publish = ".next"
  # Only build on releases (tagged commits)
  ignore = "git describe --exact-match HEAD || exit 1"
  
# Deploy previews disabled for all contexts except production
[context.deploy-preview]
  command = "exit 1"
  
[context.branch-deploy]
  command = "exit 1"

[dev]
  command = "npm run dev"
  port = 3000

# Force HTTPS redirects
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
