name: Deploy to Netlify on Release

on:
  release:
    types: [published] # Only when a release is published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Netlify Build Hook
        env:
          NETLIFY_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          if [ -z "$NETLIFY_HOOK" ]; then
            echo "⚠️ NETLIFY_BUILD_HOOK secret is not set"
            echo "🔧 To enable automatic deployment:"
            echo "1. Go to your Netlify dashboard"
            echo "2. Site settings → Build & deploy → Build hooks"
            echo "3. Create a new build hook"
            echo "4. Add the URL as NETLIFY_BUILD_HOOK secret in GitHub"
            echo ""
            echo "🎯 Manual deployment: You can manually deploy by pushing to your repository"
            echo "   since Netlify is configured to build from GitHub"
            exit 0
          else
            echo "✅ NETLIFY_BUILD_HOOK secret is configured"
          fi

      - name: Trigger Netlify Build Hook
        env:
          NETLIFY_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        if: env.NETLIFY_HOOK != ''
        run: |
          echo "🚀 Triggering Netlify deployment..."
          http_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -d '{}' "$NETLIFY_HOOK")

          if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
            echo "✅ Netlify build triggered successfully (HTTP $http_code)"
          else
            echo "❌ Failed to trigger Netlify build (HTTP $http_code)"
            echo "🔍 Build hook URL: $NETLIFY_HOOK"
            exit 1
          fi
